[package]
name = "satisfactories"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.58", features = ["derive"] }
inquire = "0.9.3"
strum = { version = "0.27.2", features = ["derive"] }
